Update pure_grain_boundary_study.ipynb
It doesn't complete because `AttributeError: 'PrimitiveNeighborList' object has no attribute 'neighbors'`. I hope this is an env problem.

I took the liberty here of playing around with extending the existing workflow object instead of making a brand new one, just for the sake of it.

Signed-off-by: liamhuber <liamhuber@greyhavensolutions.com>